export type SummaryType = {
  key: React.Key;
  jtCarrierCode: string;
  total_shipments: number;
  jtCrawledTotal: number;
  successCount: number;
  failCount: number;
  getTotalDiffFound: number;
  getTotalNODiffFound: number;
  getSentToFK: number;
  getNotSentToFK: number;
  getReferenceNotFound: number;
  getReferenceNotFoundPercentage: number;
  skipped404: number;
  successRatio: number;
  failureRatio: number;
  diffRatio: number;
  start_time: string;
  end_time: string;
  durationToLaunch: number;
  schedulerId: number;
  timeDiffMinutes: number;
  timeDiffInFk: string;
  lastRunStartAt: string;
  delayTime: number;
  lastRunStartTime: string;
  threadPoolSize: number;
  deliverCount: number;
  closeCount: number;
  queueType: string;
  hitRateCount: number;
  hitRatePer: number;
  toFKFailedScraping: number;
  toFKFailedValidation: number;
  toFKFailedNotSent: number;
  toFKFailedMapping: number;
  crawlFrequency: string;
  referenceNotFound: number;
  refPercentage: number;
  diffRateCountWithInCron: number;
  diffRateCountAboveCron: number;
  diffHitRateCountWithInCron: number;
  diffHitRateCountAboveCron: number;
  AvgAge: number;
};

export type StatusType = {
  carrier: string;
  status: string;
};
